name: Build and deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: giancosta86/aurora-github/actions/publish-github-pages@v6
        with:
          source-directory: .
