name: Deploy

on:
  pull_request:
    types: closed
    branches: main

jobs:
  publish-website:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v7

      - uses: giancosta86/aurora-github/actions/publish-github-pages@v12
